export const LOADING_LIST = "LOADING_LIST";
export const FETCH_LIST = "FETCH_LIST";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const CLEAR_LIST = "CLEAR_LIST";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
